# Webhook URL
webhookURL: 'https://geocom.uni-frankfurt.de/hooks/qoq1fd678td5bjq85qpjf4a9ye'

# Post to webhook?
post: false 

# Remember entries?
save: false

# Show new entries on command line?
log: true

# Only process journals with init flag?
init: false

# Only process journals with debug flag?
debug: false
